### ISSUE TITLE
mutidimensional NFFTs?

### ISSUE THREAD

**Issue by RainerHeintzmann** [JuliaMath/NFFT.jl#82]
I am having trouble understanding the interface of the multidimensional `NFFT`. E.g. I have a 3D array of 3D frequency positions, as an Array of tuples and want to perform the 3D `NFFT` of a 3D array sampled on  a regular grid, e.g. `(-.5:0.5)` for all coordinates.
How would this be implemented? Do I need to convert the 3D input into a 1D vector and construct Nx3 matrices for the coordinates?

**Comment by tknopp** [comment]
My initial reaction would be: yes.
But actually you should be able to `reinterprete` that data into the form required. So the nodes are stored as `Matrix{T}(D,M)`, i.e. the coordinates for each nodes are located together in packed form.

**Comment by tknopp** [comment]
```
julia> A = Vector{Tuple{Float64,Float64}}(undef,4)
4-element Vector{Tuple{Float64, Float64}}:
 (2.5560705e-314, 2.287817257e-314)
 (2.2534184583e-314, 2.3113431296e-314)
 (2.2534184583e-314, 2.2534184583e-314)
 (5.0e-324, NaN)

julia> collect(reinterpret(reshape,Float64, A))
2×4 Matrix{Float64}:
 2.55607e-314  2.25342e-314  2.25342e-314    5.0e-324
 2.28782e-314  2.31134e-314  2.25342e-314  NaN
```

Not sure if the collect is necessary.

**Comment by RainerHeintzmann** [comment]
Yes, this sounds good, but how can you then supply the necessary information to the `NFFT`?

**Comment by tknopp** [comment]
I don't understand the question. You need to pass a `Matrix{T}(D,M)` to the plan. Additionally you need to pass `N`, e.g. the size of the equidistant grid. More information is not needed.

**Comment by tknopp** [comment]
I think this example from our documentation should make this clear:
```
M, N = 16, 32
x = rand(2, M) .- 0.5
fHat = randn(ComplexF64,M)
p = plan_nfft(x, (N,N))
f = adjoint(p) * fHat
g = p * f
```
It is a 2D NFFT for N=32x32 and M=16 nodes.

**Comment by tknopp** [comment]
```
 N = 32
    xy = Tuple.(CartesianIndices((N,N)))  # 2d coordingates
    # convert 2d coordinates to matrix form
    x = reshape(reinterpret(reshape,eltype(xy[1]), xy), (2, prod(size(xy)))) ./ size(xy) .- 0.5

    p = plan_nfft(x, (N,N))
    f = randn(ComplexF64, N, N);
    fHat =  reshape(p * f, N,N)
```
The NFFT cannot know that you sampled the data equidistantly on a grid. You thus need to reshape it.

**Comment by RainerHeintzmann** [comment]
Wow it even accepts the array as input. I fell into the same trap as before, not making the input Complex-Valued. I tried it and there is a discrepancy by one pixel, but I blame it on a bad choice of my frequencies ;-). Here is the corrected code, this time transforming an array of ones:
```julia
    N = 32
    xy = Tuple.(CartesianIndices((N,N)))  # 2d coordingates
    # convert 2d coordinates to matrix form
    x = (reshape(reinterpret(reshape,eltype(xy[1]), xy), (2, prod(size(xy)))) .-1) ./ size(xy) .- 0.5

    p = plan_nfft(x, (N,N))
    f = ones(ComplexF64, N,N)
    g = reshape(p * f, N,N)
    res_error = g .- fftshift(fft(f))
```
Interestingly, the middle axis have far greater errors that the rest of the array.
Maybe it would be worth providing an additional (simpler) ND user-interface accepting the array of tuples, what do you think?
I could try writing such an ND function, if you like.

**Comment by tknopp** [comment]
Having the alternative interface would be ok for me but its not completely simple. You would need to touch these methods:

https://github.com/JuliaMath/NFFT.jl/blob/master/AbstractNFFTs/src/derived.jl#L19

We already support the conversion from an AbstractVector (i.e. a range) into the matrix format.

**Comment by JeffFessler** [comment]
> x = reshape(reinterpret(reshape,eltype(xy[1]), xy), (2, prod(size(xy)))) ./ size(xy) .- 0.5

I always learn new things from Tobi; today it is the `reinterpret` function!  Here's an alternative that feels less magical to me:
`(hcat(collect.(xy)...) .- 1) ./ size(xy) .- 0.5`

**Comment by tknopp** [comment]
Ok, now I understand what you want. My answer here is unfortunately: no. The special case of deformed tensor grids is nothing I want to leak into the NFFTPlan. This should be done outside, i.e. using the reshape outside of the NFFT. Leaking it into NFFTPlan will be a nightmare for type-stability and actually the NFFT should not have that knowledge.

Having said that it would be possible to implement a `NFFTPlanForADeformedGrid` type that does everything that you want. It could be part of `NFFTTools.jl` if that is a use case for you.

**Comment by RainerHeintzmann** [comment]
Yes, I can see the type stability issue. I gave the method a different name to intentionally discriminate it (see above). Your name or a shorter version of the plan type sounds OK to me. As we may include `NFFT` as a dependency in `FourierTools`, we can also implement the deformed grid routines entirely in `FourierTools`, if you feel this is more fitting.

**Comment by tknopp** [comment]
>  today it is the reinterpret function!

The `reinterpret` has a huge advantage: It does not allocate memory. The memory layout of an array of tuples is pointer free.

But unfortunately `reinterpret`, nowadays returns a pretty scary type that NFFT.jl right now does not support (-> type stability of the plan). Therefore the collect, which will make a copy....

But still this  should be way faster than using `cat` (no offense! I am using `cat` a lot in high-level scripting code. Just wanted to underline why `reinterpret` is useful.)

**Comment by tknopp** [comment]
Ah, thanks for the background Rainer, now things start to make sense for me. Yes, please put that into `FourierTools`. That makes much more sense in that package.

**Comment by RainerHeintzmann** [comment]
> > today it is the reinterpret function!
> 
> The `reinterpret` has a huge advantage: It does not allocate memory. The memory layout of an array of tuples is pointer free.
> 
> But unfortunately `reinterpret`, nowadays returns a pretty scary type that NFFT.jl right now does not support (-> type stability of the plan). Therefore the collect, which will make a copy....
> 
> But still this should be way faster than using `cat` (no offense! I am using `cat` a lot in high-level scripting code. Just wanted to underline why `reinterpret` is useful.)

... and it may have been the reason that `Julia` crashed, when I made a mistake ;-) `reinterpret` is somewhat scary, but very fast like a view.

**Comment by RainerHeintzmann** [comment]
> Ah, thanks for the background Rainer, now things start to make sense for me. Yes, please put that into `FourierTools`. That makes much more sense in that package.

OK. Will do. I am amazed how fast the ND version seems to be: 0.07 sec for regridding a 512x512 array. I implemented something similar based on line-wise NUFFT and got 0.6 sec. instead, but this is probably due to the need to replan 512 times.

**Comment by tknopp** [comment]
yes NFFT.jl is now pretty fast although I have to admit that this really is because of the work other researchers have made on the algorithmic level.

What would be interesting for me is: Are you also targeting "directional" NFFTs, i.e. NFFTs that are only performed in one direction but for all slices? This is a feature that we provide and I am still not clear if there are use cases for that.

**Comment by RainerHeintzmann** [comment]
I am not sure that I understand the concept of a directional NFFT. Yes, for beam propagation we may use NFFTs in one direction for a stack of slices. If the destination coordinates are similar, I would just use the plan and if not, I would think one has to recompute the plan for each transform. I don't quite see the  "directional" feature could be helpful, since I don't understand it yet.

**Comment by tknopp** [comment]
The directional feature is just an optimization. It is much faster, if you don't do the NFFT along the "inner" direction. FFTW has the same feature. It is the `dims` option you can pass to it.

**Comment by JeffFessler** [comment]
> The memory layout of an array of tuples is pointer free.

Very cool - I didn't realize, so thanks!  It feels queasy to rely on (undocumented?) specific memory layouts... It is a logical layout so hopefully it doesn't change!

**Comment by tknopp** [comment]
> (undocumented?) specific memory layouts

Julia by design uses tight, C compatible, memory layouts whenever possible to avoid boxing. This in particular holds true for `structs` and `tuples` (if and only if the members are bit types). And if in doubt, one can check with `isbits`:
```
julia> isbits( (1.0,1.0) )
true

julia> struct MyType
         a::Float64
         b::Float64
       end

julia> isbits(MyType(1.0,1.0))
true
```
And this can be very handy when working with files where it allows one to read binary headers into tuples / structs. Without that feature it would have been a nightmare to implement the ISMRMRD file format (see https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/master/src/Datatypes/RawAcqData.jl#L22 for the structs. The exactly match their C counterparts)

**Comment by JeffFessler** [comment]
> would have been a nightmare to implement the ISMRMRD file format

Awesome - thanks for the tips.  I know this nightmare from implementing some GE kspace readers:
https://github.com/JeffFessler/MIRTio.jl/blob/main/src/ge-mri/rdb-26_002.jl
Next time I need to do that I'll definitely try a struct instead!
